name = "rendro"
main = "src/worker.ts"
compatibility_date = "2025-07-05"

[observability]
enabled = true

[assets]
directory = "./public"
binding = "ASSETS"

[[r2_buckets]]
binding = "DOCS"
bucket_name = "rendro-docs"

[vars]
NODE_ENV = "production"
BASE_URL = "https://rendro.app"

[[routes]]
pattern = "rendro.app"
custom_domain = true
