name = "rendro"
main = "src/worker.ts"
compatibility_date = "2025-07-06"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[r2_buckets]]
binding = "DOCS"
bucket_name = "rendro-docs"

[[d1_databases]]
binding = "rendro_auth"
database_name = "rendro-auth"
database_id = "fdba8cd7-5ae3-4ac9-8e23-f2ea1210e334"


[vars]
NODE_ENV = "production"
BASE_URL = "https://rendro.app"
