import { Hono } from "hono";
import type { User } from "better-auth/types";
import { renderControlPlanePage, renderLoadingState } from "./control-plane";
import { organizationContextScript } from "./organization-context";
import {
  organizationSectionHeading,
  organizationSectionLoading,
  renderOrganizationLoadingPage,
} from "./management-loading";

const app = new Hono<{ Variables: { user?: User } }>();

type OrganizationPageSection = "overview" | "people" | "teams" | "settings";

export function organizationSectionDataPaths(section: OrganizationPageSection): string[] {
  const paths = ["/api/auth/organization/get-full-organization"];
  if (section === "overview" || section === "people") paths.push("/api/auth/organization/list-invitations");
  if (section === "overview") paths.push("/api/rendro/projects");
  return paths;
}

function signInHref(returnTo: string): string {
  return `/sign-in?returnTo=${encodeURIComponent(returnTo)}`;
}

function organizationRoute(organizationId: string, suffix = ""): string {
  return `/organizations/${encodeURIComponent(organizationId)}${suffix}`;
}
function organizationChooserLoading(): string {
  const card = `<article class="panel skeleton-card">
    <div class="skeleton-card-head"><span class="skeleton skeleton-icon"></span><span class="skeleton-copy"><span class="skeleton skeleton-line strong long"></span><span class="skeleton skeleton-line medium"></span></span></div>
  </article>`;
  return renderLoadingState("Loading organizations", `<div class="organization-grid">${card}${card}</div><div class="chooser-footer"><span class="skeleton skeleton-button"></span></div>`);
}

function onboardingLoading(projectReady: boolean): string {
  return renderLoadingState(projectReady ? "Loading deployment setup" : "Loading project setup", `<div class="skeleton-copy">
    <span class="skeleton skeleton-line strong medium"></span>
    <span class="skeleton skeleton-line long"></span>
    <span class="skeleton skeleton-line short"></span>
    <span class="skeleton skeleton-field"></span>
    <span class="skeleton skeleton-line short"></span>
    <span class="skeleton skeleton-field"></span>
    <span class="skeleton skeleton-button"></span>
  </div>`);
}



const organizationChooserScript = String.raw`
(function(){
  "use strict";
  var ui=window.RendroUI.createPageScope?window.RendroUI.createPageScope():window.RendroUI,state=window.__RENDRO_PAGE_STATE__,mount=document.getElementById("organization-state"),loading=${JSON.stringify(organizationChooserLoading())},loadVersion=0;
  function active(){return !ui.isActive||ui.isActive();}
  function slugify(value){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48);}
  function organizationCard(organization){var link=document.createElement("a");link.className="panel panel-pad organization-card";link.href="/organizations/"+encodeURIComponent(organization.id);link.innerHTML='<span class="cp-org-mark"></span><span class="cell-primary"><strong></strong><span class="cell-secondary"></span></span><span class="organization-arrow">Open</span>';link.querySelector(".cp-org-mark").textContent=(organization.name||"R").charAt(0).toUpperCase();link.querySelector("strong").textContent=organization.name;link.querySelector(".cell-secondary").textContent=organization.slug;return link;}
  function creationForm(onboarding){mount.innerHTML='<section class="panel panel-pad onboarding"><div class="stepper" aria-label="Setup progress"><div class="step active" aria-current="step"><span class="step-dot" aria-hidden="true">1</span><span>Organization</span></div><div class="step"><span class="step-dot" aria-hidden="true">2</span><span>Project</span></div><div class="step"><span class="step-dot" aria-hidden="true">3</span><span>First deployment</span></div></div><div class="panel-head"><div><h2>Create your organization</h2><p>This is the security boundary for people, projects, credentials, and documentation.</p></div></div><form class="form-grid" id="organization-form"><label class="field"><span>Organization name</span><input class="input" name="name" autocomplete="organization" maxlength="80" required placeholder="Acme Documentation"></label><label class="field"><span>Organization slug</span><input class="input" name="slug" maxlength="48" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="acme-docs"><small>Used in human-readable URLs. You can edit the generated value.</small></label><p class="message error" id="organization-error" role="alert"></p><div class="form-actions"><button class="button primary" type="submit"><span class="button-label">Create organization</span></button></div></form></section>';bindCreation(document.getElementById("organization-form"),onboarding);}
  function bindCreation(form,onboarding){var name=form.elements.namedItem("name"),slug=form.elements.namedItem("slug"),touched=false;slug.addEventListener("input",function(){touched=true;});name.addEventListener("input",function(){if(!touched)slug.value=slugify(name.value);});form.addEventListener("submit",async function(event){event.preventDefault();var button=form.querySelector("button[type=submit]"),error=document.getElementById("organization-error");error.textContent="";ui.busy(button,true);try{var organization=await ui.request("/api/auth/organization/create",{method:"POST",body:JSON.stringify({name:name.value.trim(),slug:slug.value.trim(),keepCurrentActiveOrganization:false})});if(!active())return;location.assign("/organizations/"+encodeURIComponent(organization.id)+(onboarding?"/onboarding":""));}catch(reason){if(!active())return;error.textContent=reason instanceof Error?reason.message:"Unable to create organization.";ui.busy(button,false);}});}
  async function load(){var version=++loadVersion;mount.innerHTML=loading;try{var organizations=await ui.request("/api/auth/organization/list"),choose=new URLSearchParams(location.search).get("choose")==="1";if(!active()||version!==loadVersion)return;if(!organizations.length){creationForm(true);return;}if(organizations.length===1&&!choose){location.replace("/organizations/"+encodeURIComponent(organizations[0].id));return;}mount.innerHTML='<div class="organization-grid" id="organization-list"></div><div class="chooser-footer"><button class="button" id="show-create" type="button">New organization</button></div>';var list=document.getElementById("organization-list");organizations.forEach(function(organization){list.appendChild(organizationCard(organization));});document.getElementById("show-create").addEventListener("click",function(){creationForm(false);});}catch(error){if(!active()||version!==loadVersion)return;mount.innerHTML='<section class="panel empty"><span class="empty-mark">!</span><h2>Unable to load organizations</h2><p></p><button class="button" type="button">Try again</button></section>';mount.querySelector("p").textContent=error.message;mount.querySelector("button").addEventListener("click",load);}}
  load();
})();
`;

function renderOrganizationsPage(user: User): string {
  return renderControlPlanePage({
    user,
    title: "Organizations",
    eyebrow: "Workspace",
    heading: "Your organizations",
    description: "Return to a workspace or create a secure boundary for a new documentation product.",
    focused: true,
    content: `<div id="organization-state">${organizationChooserLoading()}</div><style>.organization-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.organization-card{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:12px;text-decoration:none;transition:border-color var(--cp-instant) var(--cp-ease),transform var(--cp-instant) var(--cp-ease),background var(--cp-instant) var(--cp-ease)}.organization-card:hover{border-color:var(--cp-accent);background:var(--cp-accent-soft);transform:translateY(-1px)}.organization-arrow{color:var(--cp-accent);font-size:12px;font-weight:750}.chooser-footer{display:flex;justify-content:center;margin-top:18px}@media(max-width:720px){.organization-grid{grid-template-columns:1fr}}</style>`,
    script: organizationChooserScript,
  });
}

function organizationPageScript(section: OrganizationPageSection): string {
  return String.raw`
(function(){
  "use strict";
  var ui=window.RendroUI.createPageScope?window.RendroUI.createPageScope():window.RendroUI,state=window.__RENDRO_PAGE_STATE__,orgId=state.organizationId,mount=document.getElementById("organization-content"),loadVersion=0,observers=[],settingsCleanup=null,invitationPath=${JSON.stringify(section === "overview" || section === "people" ? "/api/auth/organization/list-invitations" : "")},projectsPath=${JSON.stringify(section === "overview" ? "/api/rendro/projects" : "")};
  var loadingStates={overview:${JSON.stringify(organizationSectionLoading("overview"))},people:${JSON.stringify(organizationSectionLoading("people"))},teams:${JSON.stringify(organizationSectionLoading("teams"))},settings:${JSON.stringify(organizationSectionLoading("settings"))}};
  function active(){return !ui.isActive||ui.isActive();}
  function h(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  function post(path,body){return ui.request(path,{method:"POST",body:JSON.stringify(body)});}
  function setOrganizationChrome(organization){if(!active())return;var name=organization.name||"Organization",mark=(organization.name||"R").charAt(0).toUpperCase();document.querySelectorAll("[data-org-name]").forEach(function(node){if(node.textContent!==name)node.textContent=name;});document.querySelectorAll("[data-org-mark]").forEach(function(node){if(node.textContent!==mark)node.textContent=mark;});}
  function escapeText(value){return String(value).replace(/[&<>"']/g,function(character){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[character];});}
  function syncManagementAction(canManage){var action=document.getElementById("organization-page-action");if(!action)return;action.hidden=!canManage;if("disabled" in action)action.disabled=!canManage;}
  function roleList(member){return String(member&&member.role||"").split(",").map(function(role){return role.trim();}).filter(Boolean);}
  function primaryRole(member){var roles=roleList(member);return roles.indexOf("owner")>=0?"owner":roles.indexOf("admin")>=0?"admin":roles.indexOf("member")>=0?"member":roles[0]||"member";}
  function membershipFor(organization){if(organization.member)return organization.member;return (organization.members||[]).find(function(member){return member.userId===state.userId||member.user&&member.user.id===state.userId;});}
  async function baseData(){var query="?organizationId="+encodeURIComponent(orgId),organizationRequest=state.section==="settings"?window.RendroUI.organizationContext.access(ui,orgId):window.RendroUI.organizationContext.request(ui,orgId),projectsRequest=state.section==="overview"?ui.request(projectsPath+query):Promise.resolve({projects:[]});organizationRequest.then(function(organization){if(active()&&organization)setOrganizationChrome(organization);}).catch(function(){});var initial=await Promise.all([organizationRequest,projectsRequest]),organization=initial[0];if(!active())return null;if(!organization)throw new Error("Organization not found.");var membership=membershipFor(organization);if(!membership)throw new Error("Your organization membership could not be confirmed.");var currentRole=primaryRole(membership),canManage=currentRole==="owner"||currentRole==="admin",invitationRequest=(state.section==="overview"||state.section==="people")&&canManage?ui.request(invitationPath+query).then(function(data){return {data:data};},function(error){return {error:error};}):Promise.resolve({data:[]});if(!active())return null;return {organization:organization,membership:membership,currentRole:currentRole,canManage:canManage,isOwner:currentRole==="owner",isAdmin:currentRole==="admin",invitations:[],invitationRequest:invitationRequest,projects:initial[1].projects||[]};}
  function statusEmpty(mark,title,copy,action){return '<section class="panel empty"><span class="empty-mark material-symbols-outlined" aria-hidden="true">'+escapeText(mark)+'</span><h2>'+escapeText(title)+'</h2><p>'+escapeText(copy)+'</p>'+action+'</section>';}
  function disconnectObservers(){observers.forEach(function(observer){observer.disconnect();});observers=[];}
  function observe(target,callback){if(!target)return;var observer=new MutationObserver(callback);observer.observe(target,{childList:true});observers.push(observer);}
  function watchCollectionEmpties(data){if(state.section==="people"&&data.canManage){var invitations=document.getElementById("invitation-list");observe(invitations,function(){if(active()&&!invitations.children.length)invitations.innerHTML='<tr><td colspan="4"><div class="mini-empty">No pending invitations.</div></td></tr>';});}if(state.section==="teams"){var grid=document.getElementById("team-grid");observe(grid,function(){if(active()&&!grid.querySelector(".team-card")&&!grid.querySelector(".empty")){var action=data.canManage?'<button class="button primary" type="button">Create first team</button>':"";grid.innerHTML=statusEmpty("groups","No teams yet",data.canManage?"Create a team, then assign existing organization members.":"No teams have been created for this organization.",action);var button=grid.querySelector("button");if(button)button.addEventListener("click",function(){ui.openDialog("team-dialog");});}});}}
  async function renderOverview(data,version){var org=data.organization;mount.innerHTML='<div class="grid-3 overview-metrics"><article class="panel metric"><strong>'+data.projects.length+'</strong><span>Projects</span></article><article class="panel metric"><strong>'+org.members.length+'</strong><span>Members</span></article><article class="panel metric"><strong>'+org.teams.length+'</strong><span>Teams</span></article></div><div class="overview-grid"><section class="panel panel-pad"><div class="panel-head"><div><h2>Projects</h2><p>Active documentation products in this organization.</p></div><a class="button small" href="/organizations/'+encodeURIComponent(orgId)+'/projects">All projects</a></div><div id="overview-projects" class="overview-list"></div></section><aside class="panel panel-pad"><div class="panel-head"><div><h2>Workspace status</h2><p>Complete the path to a live document.</p></div></div><div class="checklist" id="workspace-checklist"></div></aside></div><section class="panel panel-pad recent-panel"><div class="panel-head"><div><h2>Recent deployment</h2><p>The latest immutable release across your projects.</p></div></div><div id="recent-deployment"></div></section>';var projectList=document.getElementById("overview-projects");if(!data.projects.length){projectList.innerHTML='<div class="mini-empty">No projects yet. Create the first project to connect your documentation.</div>';}data.projects.slice(0,5).forEach(function(project){var link=h("a","overview-row");link.href="/organizations/"+encodeURIComponent(orgId)+"/projects/"+encodeURIComponent(project._id);var copy=h("span","cell-primary");copy.append(h("strong","",project.name),h("span","cell-secondary",project.slug));link.append(copy,h("span","badge "+(project.activeDeploymentId?"success":""),project.activeDeploymentId?"Deployed":"Not deployed"));projectList.append(link);});var checklist=document.getElementById("workspace-checklist"),items=[{done:true,label:"Organization created"},{done:data.projects.length>0,label:"Create a project"},{done:data.projects.some(function(project){return Boolean(project.activeDeploymentId);}),label:"Push the first deployment"},{done:org.members.length>1,label:"Invite a teammate",optional:true}];items.forEach(function(item){var row=h("div","checklist-row"+(item.done?" complete":""));row.append(h("span","checklist-mark",item.done?"Done":""),h("span","",item.label+(item.optional?" (optional)":"")));checklist.append(row);});data.invitationRequest.then(function(result){if(!active()||version!==loadVersion)return;if(!result.error&&result.data.some(function(invite){return invite.status==="pending";})){var row=checklist.lastChild;row.classList.add("complete");row.querySelector(".checklist-mark").textContent="Done";}});
    loadRecentDeployment(version);
  }
  var recentVersion=0;
  async function loadRecentDeployment(version){var current=++recentVersion,recent=document.getElementById("recent-deployment");recent.innerHTML='<div class="loading-view" role="status" aria-label="Loading recent deployment"><div class="skeleton skeleton-field"></div></div>';try{var result=await ui.request("/api/rendro/management/recent-deployment?organizationId="+encodeURIComponent(orgId));if(!active()||version!==loadVersion||current!==recentVersion)return;recent.innerHTML="";var latest=result.deployment;if(!latest){recent.innerHTML='<div class="mini-empty">No deployment has been committed yet.</div>';return;}var row=h("div","overview-row"),copy=h("span","cell-primary");copy.append(h("strong","",latest.projectName),h("span","cell-secondary",latest.commit?"Commit "+latest.commit:"Immutable deployment"));row.append(copy,h("span","badge "+(latest.status==="active"?"success":""),latest.status==="active"?"Active":latest.status));recent.append(row);}catch(error){if(!active()||version!==loadVersion||current!==recentVersion)return;recent.innerHTML='<div class="mini-empty" role="status"><p>Recent deployment could not be loaded.</p><button class="button" type="button">Try again</button></div>';recent.querySelector("button").onclick=function(){loadRecentDeployment(version);};}}

  function syncInviteRowControls(rows){var entries=Array.from(rows.querySelectorAll(".invite-entry")),add=document.getElementById("add-invite-row");entries.forEach(function(entry){entry.querySelector(".remove-invite").disabled=entries.length<=1;});if(add)add.disabled=entries.length>=10;}
  function inviteRow(rows){var row=h("div","invite-entry");row.innerHTML='<label class="field"><span>Work email</span><input class="input" type="email" name="email" required autocomplete="off" placeholder="person@company.com"></label><label class="field"><span>Role</span><select class="select" name="role"><option value="member">Member</option><option value="admin">Admin</option></select></label><button class="button ghost remove-invite" type="button" aria-label="Remove invitation row">Remove</button>';row.querySelector(".remove-invite").addEventListener("click",function(){if(rows.children.length>1){row.remove();syncInviteRowControls(rows);}});return row;}
  function renderMemberRows(data){
    var org=data.organization,members=document.getElementById("member-list"),ownerCount=org.members.filter(function(member){return roleList(member).indexOf("owner")>=0;}).length;members.innerHTML="";var count=document.getElementById("member-count");if(count)count.textContent=org.members.length+(org.members.length===1?" person currently has organization access.":" people currently have organization access.");
    org.members.forEach(function(member){
      var tr=h("tr"),person=h("td");person.dataset.label="User";var copy=h("span","cell-primary");copy.append(h("strong","",member.user&&member.user.name||"Member"),h("span","cell-secondary",member.user&&member.user.email||member.userId));person.append(copy);
      var roleCell=h("td"),memberRole=primaryRole(member),targetIsOwner=roleList(member).indexOf("owner")>=0,canEdit=data.isOwner||data.isAdmin&&!targetIsOwner;roleCell.dataset.label="Role";
      if(canEdit){
        var confirmedRole=memberRole,select=h("select","select role-select"),availableRoles=data.isOwner?["member","admin","owner"]:["member","admin"];
        availableRoles.forEach(function(role){var option=h("option","",role.charAt(0).toUpperCase()+role.slice(1));option.value=role;option.selected=role===confirmedRole;if(data.isOwner&&targetIsOwner&&ownerCount<=1&&role!=="owner")option.disabled=true;select.append(option);});
        select.value=confirmedRole;select.setAttribute("aria-label","Change role for "+(member.user&&member.user.email||"member"));
        select.addEventListener("change",async function(){var requestedRole=select.value;select.disabled=true;try{var updated=await post("/api/auth/organization/update-member-role",{memberId:member.id,role:requestedRole,organizationId:orgId});if(!active())return;var updatedMember=updated&&updated.member||updated||{role:requestedRole};confirmedRole=primaryRole(updatedMember);member.role=updatedMember.role||confirmedRole;if(member.userId===state.userId){data.currentRole=confirmedRole;data.isOwner=confirmedRole==="owner";data.isAdmin=confirmedRole==="admin";data.canManage=data.isOwner||data.isAdmin;}ui.toast("Member role updated.");renderMemberRows(data);if(!data.canManage){var pendingPanel=mount.querySelector(".pending-panel");if(pendingPanel)pendingPanel.remove();var dialog=document.getElementById("invite-dialog");if(dialog)dialog.remove();}syncManagementAction(data.canManage);}catch(error){if(!active())return;select.value=confirmedRole;select.disabled=false;ui.toast(error.message,"error");}});
        roleCell.append(select);
      }else roleCell.append(h("span","badge",memberRole.charAt(0).toUpperCase()+memberRole.slice(1)));
      var joined=h("td","",member.createdAt?new Date(member.createdAt).toLocaleDateString():"—");joined.dataset.label="Joined";var access=h("td");access.dataset.label="Access";access.append(h("span","badge success","Active"));if(canEdit&&member.userId!==state.userId&&!(targetIsOwner&&ownerCount<=1)){var remove=h("button","button danger small remove-member","Remove");remove.setAttribute("aria-label","Remove "+(member.user&&member.user.name||"member")+" from organization");remove.addEventListener("click",async function(){if(!confirm("Remove "+(member.user&&member.user.name||"this member")+" from the organization? They will lose access to its projects and teams."))return;ui.busy(remove,true);try{await post("/api/auth/organization/remove-member",{organizationId:orgId,memberIdOrEmail:member.id});if(!active())return;org.members=org.members.filter(function(candidate){return candidate.id!==member.id;});renderMemberRows(data);ui.toast("Organization member removed.");}catch(error){if(!active())return;ui.busy(remove,false);ui.toast(error.message,"error");}});access.append(remove);}tr.append(person,roleCell,joined,access);members.append(tr);
    });
  }
  async function renderPeople(data,version){
    var org=data.organization,pending=data.invitations.filter(function(invitation){return invitation.status==="pending";}),pendingPanel=data.canManage?'<section class="panel pending-panel"><div class="panel-head panel-pad people-head"><div><h2>Pending invitations</h2><p>Invitations expire after seven days and can be revoked immediately.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody id="invitation-list"></tbody></table></div></section>':"";
    mount.innerHTML='<section class="panel"><div class="panel-head panel-pad people-head"><div><h2>Members</h2><p id="member-count">'+org.members.length+' people currently have organization access.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>User</th><th>Role</th><th>Joined</th><th>Access</th></tr></thead><tbody id="member-list"></tbody></table></div></section>'+pendingPanel;renderMemberRows(data);
    if(!data.canManage){var dialog=document.getElementById("invite-dialog");if(dialog)dialog.remove();return;}
    var invitations=document.getElementById("invitation-list");invitations.innerHTML='<tr><td colspan="4"><div class="loading-view" role="status" aria-label="Loading invitations"><div class="skeleton skeleton-field"></div></div></td></tr>';var invitationResult=await data.invitationRequest;if(!active()||version!==loadVersion)return;invitations.innerHTML="";if(invitationResult.error){invitations.innerHTML='<tr><td colspan="4"><div class="mini-empty" role="status"><p>Invitations could not be loaded.</p><button class="button" type="button">Try again</button></div></td></tr>';invitations.querySelector("button").onclick=load;}pending=(invitationResult.data||[]).filter(function(invite){return invite.status==="pending";});if(!invitationResult.error&&!pending.length){var empty=h("tr");empty.innerHTML='<td colspan="4"><div class="mini-empty">No pending invitations.</div></td>';invitations.append(empty);}
    pending.forEach(function(invitation){var tr=h("tr");tr.innerHTML='<td data-label="Email"><span class="cell-primary"><strong></strong><span class="cell-secondary"></span></span></td><td data-label="Role"></td><td data-label="Status"><span class="badge warning">Pending</span></td><td data-label="Action"></td>';tr.querySelector("strong").textContent=invitation.email;tr.querySelector(".cell-secondary").textContent="Invited "+(invitation.createdAt?new Date(invitation.createdAt).toLocaleDateString():"");tr.children[1].textContent=invitation.role||"member";var revoke=h("button","button danger small","Revoke");revoke.addEventListener("click",async function(){if(!confirm("Revoke the invitation for "+invitation.email+"?"))return;ui.busy(revoke,true);try{await post("/api/auth/organization/cancel-invitation",{invitationId:invitation.id});if(!active())return;tr.remove();ui.toast("Invitation revoked.");}catch(error){if(!active())return;ui.busy(revoke,false);ui.toast(error.message,"error");}});tr.children[3].append(revoke);invitations.append(tr);});
    var rows=document.getElementById("invite-rows"),addRow=document.getElementById("add-invite-row");rows.innerHTML="";rows.append(inviteRow(rows));syncInviteRowControls(rows);addRow.addEventListener("click",function(){if(rows.children.length<10){rows.append(inviteRow(rows));syncInviteRowControls(rows);}});var form=document.getElementById("invite-form");form.addEventListener("submit",async function(event){event.preventDefault();var button=form.querySelector("button[type=submit]"),error=document.getElementById("invite-error"),entries=Array.from(rows.querySelectorAll(".invite-entry"));error.textContent="";ui.busy(button,true);var failures=[];for(var entry of entries){var email=entry.querySelector("[name=email]").value.trim(),role=entry.querySelector("[name=role]").value;try{await post("/api/auth/organization/invite-member",{email:email,role:role,organizationId:orgId});if(!active())return;entry.remove();}catch(reason){if(!active())return;failures.push(email+": "+reason.message);entry.querySelector("[name=email]").setAttribute("aria-invalid","true");}}if(!active())return;if(failures.length){error.textContent=failures.join(" ");ui.toast((entries.length-failures.length)+" invitation"+(entries.length-failures.length===1?"":"s")+" sent; retry the highlighted rows.");if(!rows.children.length)rows.append(inviteRow(rows));syncInviteRowControls(rows);ui.busy(button,false);return;}document.getElementById("invite-dialog").close();ui.toast(entries.length===1?"Invitation sent.":entries.length+" invitations sent.");await load();});
  }
  async function renderTeams(data){
    var org=data.organization;mount.innerHTML='<div class="team-grid" id="team-grid"></div>';var grid=document.getElementById("team-grid");
    if(!org.teams.length){var action=data.canManage?'<button class="button primary" type="button" data-dialog-open="team-dialog">Create first team</button>':"";grid.innerHTML=statusEmpty("groups","No teams yet",data.canManage?"Create a team, then assign existing organization members.":"No teams have been created for this organization.",action);var firstButton=grid.querySelector("button");if(firstButton)firstButton.addEventListener("click",function(){ui.openDialog("team-dialog");});}
    org.teams.forEach(function(team){var card=h("article","panel panel-pad team-card"),controls=data.canManage?'<div class="team-assign"><select class="select" aria-label="Choose member"><option value="">Choose member</option></select><button class="button" type="button" disabled>Add member</button></div><div class="team-footer"><button class="button danger small remove-team" type="button">Remove team</button></div>':"";card.innerHTML='<div class="panel-head"><div><h2></h2><p>'+(data.canManage?"Assign organization members to this team.":"Organization team")+'</p></div><span class="badge">Team</span></div>'+controls;card.querySelector("h2").textContent=team.name;if(data.canManage){var select=card.querySelector("select");org.members.forEach(function(member){var option=h("option","",member.user&&member.user.name||member.userId);option.value=member.userId;select.append(option);});var add=card.querySelector(".team-assign .button");select.addEventListener("change",function(){add.disabled=!select.value;});add.addEventListener("click",async function(){if(!select.value)return;ui.busy(add,true);try{await post("/api/auth/organization/add-team-member",{teamId:team.id,userId:select.value,organizationId:orgId});if(!active())return;ui.toast("Member added to "+team.name+".");select.value="";card.dispatchEvent(new Event("rendro:team-changed"));}catch(error){if(!active())return;ui.toast(error.message,"error");}ui.busy(add,false);add.disabled=!select.value;});var remove=card.querySelector(".remove-team");remove.addEventListener("click",async function(){if(!confirm("Remove team "+team.name+"? Organization members keep their access."))return;ui.busy(remove,true);try{await post("/api/auth/organization/remove-team",{teamId:team.id,organizationId:orgId});if(!active())return;card.style.opacity="0";var removalTimer=setTimeout(function(){if(active())card.remove();},200);if(ui.onCleanup)ui.onCleanup(function(){clearTimeout(removalTimer);});ui.toast("Team removed.");}catch(error){if(!active())return;ui.busy(remove,false);ui.toast(error.message,"error");}});}grid.append(card);if(data.canManage)bindTeamRoster(card,team,data);});
    if(!data.canManage){var dialog=document.getElementById("team-dialog");if(dialog)dialog.remove();return;}
    var form=document.getElementById("team-form");if(!form.dataset.submitReady){form.dataset.submitReady="true";form.addEventListener("submit",async function(event){event.preventDefault();var button=form.querySelector("button[type=submit]"),error=document.getElementById("team-error");if(button.getAttribute("aria-busy")==="true")return;error.textContent="";ui.busy(button,true);try{await post("/api/auth/organization/create-team",{name:form.elements.namedItem("name").value.trim(),organizationId:orgId});if(!active())return;ui.busy(button,false);form.elements.namedItem("name").value="";document.getElementById("team-dialog").close();ui.toast("Team created.");await load();}catch(reason){if(!active())return;error.textContent=reason.message;ui.busy(button,false);}});}
  }
  function bindTeamRoster(card,team,data){
    var toggle=h("button","button small","View members"),roster=h("div","team-roster"),loaded=false,version=0,rows=[],nextCursor=null;roster.hidden=true;toggle.setAttribute("aria-expanded","false");card.append(toggle,roster);
    function paint(){roster.innerHTML="";if(!rows.length)roster.append(h("p","mini-empty","No members in this team."));rows.forEach(function(member){var person=data.organization.members.find(function(candidate){return candidate.userId===member.userId;}),name=person&&person.user&&person.user.name||member.userId,row=h("div","overview-row"),label=h("span","cell-primary"),remove=h("button","button danger small","Remove");label.append(h("strong","",name));remove.setAttribute("aria-label","Remove "+name+" from "+team.name);row.append(label,remove);roster.append(row);remove.addEventListener("click",async function(){if(!confirm("Remove "+name+" from "+team.name+"? Organization access is unchanged."))return;ui.busy(remove,true);try{await post("/api/auth/organization/remove-team-member",{organizationId:orgId,teamId:team.id,userId:member.userId});if(!active())return;ui.toast("Team member removed.");await loadMembers(false);}catch(error){if(!active())return;ui.busy(remove,false);ui.toast(error.message,"error");}});});if(nextCursor!==null){var more=h("button","button small","Load more members");more.onclick=function(){loadMembers(true);};roster.append(more);}var select=card.querySelector("select");Array.from(select.options).forEach(function(option){option.disabled=rows.some(function(member){return member.userId===option.value;});});}
    async function loadMembers(append){var current=++version;loaded=true;roster.hidden=false;toggle.setAttribute("aria-expanded","true");toggle.textContent="Hide members";if(!append)roster.innerHTML='<p class="mini-empty" role="status">Loading members…</p>';else roster.querySelectorAll("button").forEach(function(button){button.disabled=true;});try{var result=await ui.request("/api/rendro/management/team-members?organizationId="+encodeURIComponent(orgId)+"&teamId="+encodeURIComponent(team.id)+(append&&nextCursor?"&cursor="+encodeURIComponent(nextCursor):""));if(!active()||current!==version)return;rows=append?rows.concat(result.members):result.members;nextCursor=result.nextCursor;paint();}catch(error){if(!active()||current!==version)return;roster.innerHTML="";roster.append(h("p","message error","Unable to load team members."));var retry=h("button","button small","Try again");retry.onclick=function(){loadMembers(false);};roster.append(retry);}}
    toggle.addEventListener("click",function(){if(!loaded){loadMembers(false);return;}roster.hidden=!roster.hidden;toggle.setAttribute("aria-expanded",String(!roster.hidden));toggle.textContent=roster.hidden?"View members":"Hide members";});card.addEventListener("rendro:team-changed",function(){loadMembers(false);});
  }
  async function renderSettings(data){
    var org=data.organization,save=data.canManage?'<p class="message error" id="settings-error" role="alert"></p><div class="form-actions"><button class="button primary" type="submit"><span class="button-label">Save changes</span></button></div>':'<p class="mini-empty">Only organization owners and admins can change these settings.</p>';
    mount.innerHTML='<section class="panel panel-pad settings-panel"><div class="panel-head"><div><h2>Organization profile</h2><p>Changing these values does not change the immutable organization ID used for authorization and storage.</p></div></div><form class="form-grid" id="settings-form"><label class="field"><span>Name</span><input class="input" name="name" maxlength="80" required'+(data.canManage?'':' disabled')+'></label><label class="field"><span>Slug</span><input class="input" name="slug" maxlength="48" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"'+(data.canManage?'':' disabled')+'></label>'+save+'</form></section>';var form=document.getElementById("settings-form");form.elements.namedItem("name").value=org.name;form.elements.namedItem("slug").value=org.slug;if(!data.canManage)return;var cleanName=form.elements.namedItem("name").value,cleanSlug=form.elements.namedItem("slug").value;function dirty(){return form.elements.namedItem("name").value!==cleanName||form.elements.namedItem("slug").value!==cleanSlug;}if(ui.preventNavigation)settingsCleanup=ui.preventNavigation(function(detail){if(!dirty())return true;return detail&&detail.kind==="unload"?false:confirm("Discard unsaved organization changes?");});form.addEventListener("submit",async function(event){event.preventDefault();var button=form.querySelector("button[type=submit]"),error=document.getElementById("settings-error");error.textContent="";ui.busy(button,true);try{var updated=await post("/api/auth/organization/update",{organizationId:orgId,data:{name:form.elements.namedItem("name").value.trim(),slug:form.elements.namedItem("slug").value.trim()}});if(!active())return;form.elements.namedItem("name").value=updated.name;form.elements.namedItem("slug").value=updated.slug;cleanName=updated.name;cleanSlug=updated.slug;window.RendroUI.organizationContext.remember(updated);setOrganizationChrome(updated);ui.toast("Organization settings saved.");}catch(reason){if(!active())return;error.textContent=reason.message;}ui.busy(button,false);});
  }
  async function load(){var version=++loadVersion;disconnectObservers();if(settingsCleanup){settingsCleanup();settingsCleanup=null;}if(version>1||!mount.querySelector(".loading-view"))mount.innerHTML=loadingStates[state.section]||loadingStates.overview;try{var data=await baseData();if(!active()||version!==loadVersion||!data)return;if(state.section==="people")await renderPeople(data,version);else if(state.section==="teams")await renderTeams(data);else if(state.section==="settings")await renderSettings(data);else await renderOverview(data,version);if(!active()||version!==loadVersion)return;watchCollectionEmpties(data);syncManagementAction(data.canManage);}catch(error){if(!active()||version!==loadVersion)return;mount.innerHTML=statusEmpty("error","Unable to load this organization",error.message,'<button class="button" type="button" id="retry">Try again</button>');document.getElementById("retry").addEventListener("click",load);}}
  if(ui.onCleanup)ui.onCleanup(disconnectObservers);
  var knownDisplay=window.RendroUI.organizationContext.display(orgId);if(knownDisplay)setOrganizationChrome(knownDisplay);
  load();
})();
`;
}

function organizationDialogs(section: OrganizationPageSection): string {
  if (section === "people") return `<dialog class="cp-dialog" id="invite-dialog"><div class="dialog-head"><div><h2>Invite people</h2><p>Each invitation is bound to its exact email address and expires after seven days.</p></div><button class="dialog-close" type="button" data-dialog-close aria-label="Close invitation dialog">Close</button></div><form id="invite-form"><div class="dialog-body"><div class="form-grid" id="invite-rows"></div><button class="button ghost small" id="add-invite-row" type="button">Add another person</button><p class="message error" id="invite-error" role="alert"></p></div><div class="dialog-footer"><button class="button" type="button" data-dialog-close>Cancel</button><button class="button primary" type="submit"><span class="button-label">Send invitations</span></button></div></form></dialog>`;
  if (section === "teams") return `<dialog class="cp-dialog" id="team-dialog"><div class="dialog-head"><div><h2>Create team</h2><p>Teams organize existing members without changing their organization role.</p></div><button class="dialog-close" type="button" data-dialog-close aria-label="Close team dialog">Close</button></div><form id="team-form"><div class="dialog-body"><label class="field"><span>Team name</span><input class="input" name="name" maxlength="80" required autofocus placeholder="Documentation"></label><p class="message error" id="team-error" role="alert"></p></div><div class="dialog-footer"><button class="button" type="button" data-dialog-close>Cancel</button><button class="button primary" type="submit"><span class="button-label">Create team</span></button></div></form></dialog>`;
  return "";
}

function renderOrganizationSection(user: User, organizationId: string, section: OrganizationPageSection): string {
  const heading = organizationSectionHeading(section, organizationId);
  const loadingPage = renderOrganizationLoadingPage(organizationId, section);
  return renderControlPlanePage({
    user,
    title: heading.heading,
    eyebrow: heading.eyebrow,
    heading: heading.heading,
    description: heading.description,
    organizationId,
    active: heading.active,
    actions: heading.actions,
    state: { organizationId, section, userId: user.id },
    content: loadingPage.content + organizationDialogs(section),
    script: organizationContextScript + organizationPageScript(section),
  });
}

const onboardingScript = String.raw`
(function(){
  "use strict";
  var ui=window.RendroUI.createPageScope?window.RendroUI.createPageScope():window.RendroUI,state=window.__RENDRO_PAGE_STATE__,orgId=state.organizationId,projectId=state.projectId,mount=document.getElementById("onboarding-stage"),pollTimer=null,keyConfirmed=true,loading=projectId?${JSON.stringify(onboardingLoading(true))}:${JSON.stringify(onboardingLoading(false))};
  function active(){return !ui.isActive||ui.isActive();}
  function slugify(value){return value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,48);}
  function setOrg(organization){if(!active())return;var name=organization.name||"Organization",mark=(organization.name||"R").charAt(0).toUpperCase();document.querySelectorAll("[data-org-name]").forEach(function(node){if(node.textContent!==name)node.textContent=name;});document.querySelectorAll("[data-org-mark]").forEach(function(node){if(node.textContent!==mark)node.textContent=mark;});}
  function projectStage(){mount.innerHTML='<div class="panel-head"><div><h2>Create your first project</h2><p>A project owns an immutable deployment history, publications, and private shares.</p></div></div><form class="form-grid" id="project-form"><label class="field"><span>Project name</span><input class="input" name="name" maxlength="80" required autofocus placeholder="Product documentation"></label><label class="field"><span>Project slug</span><input class="input" name="slug" maxlength="48" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" placeholder="product-docs"></label><p class="message error" id="project-error" role="alert"></p><div class="form-actions"><a class="button" href="/organizations/'+encodeURIComponent(orgId)+'">Finish later</a><button class="button primary" type="submit"><span class="button-label">Create project</span></button></div></form>';var form=document.getElementById("project-form"),name=form.name,slug=form.slug,touched=false;slug.addEventListener("input",function(){touched=true;});name.addEventListener("input",function(){if(!touched)slug.value=slugify(name.value);});form.addEventListener("submit",async function(event){event.preventDefault();var button=form.querySelector("button[type=submit]"),error=document.getElementById("project-error");error.textContent="";ui.busy(button,true);try{var result=await ui.request("/api/rendro/projects",{method:"POST",body:JSON.stringify({organizationId:orgId,name:name.value.trim(),slug:slug.value.trim()})});if(!active())return;location.assign("/organizations/"+encodeURIComponent(orgId)+"/onboarding?projectId="+encodeURIComponent(result.project._id));}catch(reason){if(!active())return;error.textContent=reason.message;ui.busy(button,false);}});}
  function deploymentStage(){mount.innerHTML='<div class="panel-head"><div><h2>Connect the Rendro CLI</h2><p>Create a project-scoped credential, store it once, then push real documentation.</p></div></div><form class="form-grid" id="key-form"><label class="field"><span>Credential name</span><input class="input" name="name" maxlength="80" required value="First deployment"></label><label class="field"><span>Expiration</span><select class="select" name="expiry"><option value="30">30 days</option><option value="90" selected>90 days</option><option value="365">1 year</option><option value="">Never</option></select></label><div><p class="field-label">Permissions</p><label class="check"><input type="checkbox" name="scope" value="docs:read" checked> Read documentation</label><label class="check"><input type="checkbox" name="scope" value="docs:write" checked> Publish documentation</label></div><p class="message error" id="key-error" role="alert"></p><div class="form-actions"><button class="button primary" type="submit"><span class="button-label">Generate API key</span></button></div></form><div id="deployment-connect" hidden></div>';var form=document.getElementById("key-form");form.addEventListener("submit",async function(event){event.preventDefault();var button=form.querySelector("button[type=submit]"),error=document.getElementById("key-error"),scopes=Array.from(form.querySelectorAll("[name=scope]:checked")).map(function(input){return input.value;}),expiry=form.expiry.value;error.textContent="";if(!scopes.length){error.textContent="Choose at least one permission.";return;}ui.busy(button,true);try{var result=await ui.request("/api/rendro/credentials",{method:"POST",body:JSON.stringify({organizationId:orgId,projectId:projectId,name:form.elements.namedItem("name").value.trim(),scopes:scopes,expiresAt:expiry?Date.now()+Number(expiry)*86400000:undefined})});if(!active())return;ui.busy(button,false);showCredential(result.rawKey);}catch(reason){if(!active())return;error.textContent=reason.message;ui.busy(button,false);}});}
  function showCredential(rawKey){var form=document.getElementById("key-form"),connect=document.getElementById("deployment-connect"),command='export RENDRO_API_KEY="'+rawKey+'"\nrendro push --source ./docs --organization '+orgId+' --project '+projectId;keyConfirmed=false;form.hidden=true;connect.hidden=false;connect.innerHTML='<div class="secret-box"><strong>API key created</strong><span>This secret is shown once. Store it in your CI secret manager before leaving this page.</span><div class="secret-value"><code id="onboarding-key"></code><button class="button" id="copy-key" type="button">Copy key</button></div><label class="check secret-confirm"><input id="onboarding-key-confirmed" type="checkbox"> I have stored this key securely</label></div><div class="command onboarding-command"><code id="onboarding-command"></code><button class="button small" id="copy-command" type="button">Copy command</button></div><div class="progress-state"><span class="progress-dot"></span><span class="cell-primary"><strong>Waiting for your first deployment</strong><span class="cell-secondary">This status changes only after Rendro receives and commits a real CLI push.</span></span></div><div id="deployment-success"></div>';document.getElementById("onboarding-key").textContent=rawKey;document.getElementById("onboarding-command").textContent=command;document.getElementById("onboarding-key-confirmed").addEventListener("change",function(){keyConfirmed=this.checked;});function copy(id,button,label){ui.copyText(button,document.getElementById(id).textContent,label).catch(function(){ui.toast("Unable to copy. Select the value and copy it manually.","error");});}document.getElementById("copy-key").addEventListener("click",function(){copy("onboarding-key",this,"Copy key");});document.getElementById("copy-command").addEventListener("click",function(){copy("onboarding-command",this,"Copy command");});pollDeployment();}
  function schedulePoll(){if(!active())return;pollTimer=setTimeout(pollDeployment,5000);}
  async function pollDeployment(){if(!active())return;if(document.hidden){schedulePoll();return;}try{var query="?organizationId="+encodeURIComponent(orgId)+"&projectId="+encodeURIComponent(projectId),data=await ui.request("/api/rendro/deployments"+query);if(!active())return;var deployment=(data.deployments||[]).find(function(candidate){return candidate.status==="active";}),progress=document.querySelector(".progress-state");if(progress){progress.classList.remove("poll-error");progress.querySelector("strong").textContent="Waiting for your first deployment";progress.querySelector(".cell-secondary").textContent="This status changes only after Rendro receives and commits a real CLI push.";}if(deployment){if(progress)progress.remove();var success=document.getElementById("deployment-success");if(!success)return;success.className="deployment-success";success.setAttribute("role","status");success.innerHTML='<span class="step-dot material-symbols-outlined" aria-hidden="true">check</span><span class="cell-primary"><strong>First deployment received</strong><span class="cell-secondary"></span></span><a class="button primary" href="/organizations/'+encodeURIComponent(orgId)+'/projects/'+encodeURIComponent(projectId)+'/docs">Open documentation</a>';success.querySelector(".cell-secondary").textContent=(deployment.fileCount||0)+" documents"+(deployment.provenance&&deployment.provenance.commit?" · commit "+deployment.provenance.commit:"");return;}}catch(error){if(!active())return;var progress=document.querySelector(".progress-state");if(progress){progress.classList.add("poll-error");progress.querySelector("strong").textContent="Connection interrupted";progress.querySelector(".cell-secondary").textContent="Unable to check deployment status. Rendro will retry automatically.";}}schedulePoll();}
  async function init(){mount.innerHTML=loading;try{var organization=await window.RendroUI.organizationContext.request(ui,orgId);if(!active())return;setOrg(organization);var membership=(organization.members||[]).find(function(member){return member.userId===state.userId||member.user&&member.user.id===state.userId;}),roles=String(membership&&membership.role||"").split(",").map(function(role){return role.trim();});if(roles.indexOf("owner")<0&&roles.indexOf("admin")<0){mount.innerHTML='<section class="empty compact"><span class="empty-mark material-symbols-outlined" aria-hidden="true">lock</span><h2>Setup is managed by organization admins</h2><p>You can browse this workspace, but only an owner or admin can create projects and deployment credentials.</p><a class="button" href="/organizations/'+encodeURIComponent(orgId)+'">Return to overview</a></section>';return;}if(projectId)deploymentStage();else projectStage();}catch(error){if(!active())return;mount.innerHTML='<section class="empty"><span class="empty-mark material-symbols-outlined" aria-hidden="true">error</span><h2>Unable to load setup</h2><p></p><button class="button" type="button">Try again</button></section>';mount.querySelector("p").textContent=error.message;mount.querySelector("button").addEventListener("click",init);}}
  function beforeUnload(event){if(!keyConfirmed){event.preventDefault();event.returnValue="";}}
  window.addEventListener("beforeunload",beforeUnload);if(ui.onCleanup)ui.onCleanup(function(){clearTimeout(pollTimer);window.removeEventListener("beforeunload",beforeUnload);});if(ui.preventNavigation)ui.preventNavigation(function(){return keyConfirmed;});var knownDisplay=window.RendroUI.organizationContext.display(orgId);if(knownDisplay)setOrg(knownDisplay);init();
})();
`;

function renderOnboardingPage(user: User, organizationId: string, projectId?: string): string {
  const projectReady = Boolean(projectId);
  return renderControlPlanePage({
    user,
    title: "Set up Rendro",
    eyebrow: "Workspace setup",
    heading: projectReady ? "Ship your first documentation" : "Create your first project",
    description: "A focused path from a secure organization to a real, immutable documentation deployment.",
    organizationId,
    focused: true,
    state: { organizationId, projectId: projectId ?? "", userId: user.id },
    content: `<section class="onboarding"><div class="stepper" aria-label="Setup progress"><div class="step complete"><span class="step-dot material-symbols-outlined" aria-hidden="true">check</span><span>Organization<span class="sr-only"> completed</span></span></div><div class="step ${projectReady ? "complete" : "active"}"${projectReady ? "" : ' aria-current="step"'}><span class="step-dot${projectReady ? " material-symbols-outlined" : ""}" aria-hidden="true">${projectReady ? "check" : "2"}</span><span>Project${projectReady ? '<span class="sr-only"> completed</span>' : ""}</span></div><div class="step ${projectReady ? "active" : ""}"${projectReady ? ' aria-current="step"' : ""}><span class="step-dot" aria-hidden="true">3</span><span>First deployment</span></div></div><div class="panel panel-pad" id="onboarding-stage">${onboardingLoading(projectReady)}</div></section><style>.field-label{margin:0 0 8px;color:var(--cp-strong);font-weight:650}.onboarding-command{margin-top:14px}.deployment-success{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:12px;margin-top:16px;padding:16px;border:1px solid color-mix(in srgb,var(--cp-success) 40%,var(--cp-border));border-radius:10px;background:var(--cp-success-soft)}.deployment-success .step-dot{flex:none;border-color:var(--cp-success);background:var(--cp-success);color:var(--cp-on-accent);font-size:20px}@media(max-width:620px){.deployment-success{grid-template-columns:auto minmax(0,1fr)}.deployment-success .button{grid-column:1/-1}}</style>`,
    script: organizationContextScript + onboardingScript,
  });
}

const invitationScript = String.raw`
(function(){
  "use strict";
  var ui=window.RendroUI.createPageScope?window.RendroUI.createPageScope():window.RendroUI,state=window.__RENDRO_PAGE_STATE__,mount=document.getElementById("invitation-state"),loadVersion=0;
  function active(){return !ui.isActive||ui.isActive();}
  async function load(){var version=++loadVersion;try{var invitation=await ui.request("/api/auth/organization/get-invitation?id="+encodeURIComponent(state.invitationId));if(!active()||version!==loadVersion)return;mount.innerHTML='<div class="invitation-mark"></div><p class="eyebrow">Organization invitation</p><h2></h2><p class="invitation-copy"></p><div class="invitation-actions"><button class="button" id="reject" type="button">Decline</button><button class="button primary" id="accept" type="button"><span class="button-label">Accept invitation</span></button></div><p class="message error" id="invitation-error" role="alert"></p>';mount.querySelector(".invitation-mark").textContent=(invitation.organizationName||"R").charAt(0).toUpperCase();mount.querySelector("h2").textContent="Join "+(invitation.organizationName||"this organization");mount.querySelector(".invitation-copy").textContent="Accept the invitation for "+invitation.email+" with the "+(invitation.role||"member")+" role.";document.getElementById("accept").addEventListener("click",function(){respond("accept-invitation",this);});document.getElementById("reject").addEventListener("click",function(){respond("reject-invitation",this);});}catch(error){if(!active()||version!==loadVersion)return;mount.innerHTML='<span class="empty-mark material-symbols-outlined" aria-hidden="true">error</span><h2>Invitation unavailable</h2><p class="invitation-copy"></p><a class="button" href="/organizations">Return to organizations</a>';mount.querySelector("p").textContent=error.message;}}
  async function respond(action,button){var buttons=mount.querySelectorAll(".invitation-actions button");buttons.forEach(function(candidate){candidate.disabled=true;});button.setAttribute("aria-busy","true");try{var result=await ui.request("/api/auth/organization/"+action,{method:"POST",body:JSON.stringify({invitationId:state.invitationId})});if(!active())return;if(action==="accept-invitation"){location.assign("/organizations/"+encodeURIComponent(result.member.organizationId));}else location.assign("/organizations");}catch(error){if(!active())return;document.getElementById("invitation-error").textContent=error.message;buttons.forEach(function(candidate){candidate.disabled=false;});button.setAttribute("aria-busy","false");}}
  load();
})();
`;

function renderInvitationPage(user: User, invitationId: string): string {
  return renderControlPlanePage({
    user,
    title: "Organization invitation",
    eyebrow: "Invitation",
    heading: "Continue to your organization",
    description: `Signed in as ${user.email}. Review the organization and role before accepting.`,
    focused: true,
    state: { invitationId },
    content: `<section class="panel panel-pad invitation-card" id="invitation-state">${renderLoadingState("Loading invitation", `<span class="skeleton invitation-mark"></span><span class="skeleton-copy"><span class="skeleton skeleton-line strong medium"></span><span class="skeleton skeleton-line long"></span><span class="skeleton skeleton-line medium"></span></span><span class="skeleton skeleton-button"></span>`)}</section><style>.invitation-card{width:min(520px,100%);margin:20px auto;text-align:center}.invitation-card .loading-view{justify-items:center}.invitation-card .skeleton-copy{width:min(360px,100%);justify-items:center}.invitation-mark{width:52px;height:52px;display:grid;place-items:center;margin:0 auto 18px;border-radius:14px;background:var(--cp-accent-soft);color:var(--cp-accent);font-size:20px;font-weight:800}.invitation-card h2{margin:0;color:var(--cp-strong);font-size:24px}.invitation-copy{margin:9px auto 22px;color:var(--cp-muted)}.invitation-actions{display:flex;justify-content:center;gap:8px}</style>`,
    script: invitationScript,
  });
}

app.get("/organizations", (c) => {
  const user = c.get("user");
  if (!user) return c.redirect(signInHref("/organizations"));
  return c.html(renderOrganizationsPage(user));
});

app.get("/organizations/:organizationId/onboarding", (c) => {
  const user = c.get("user");
  const organizationId = c.req.param("organizationId");
  if (!user) return c.redirect(signInHref(organizationRoute(organizationId, "/onboarding")));
  return c.html(renderOnboardingPage(user, organizationId, c.req.query("projectId")));
});

for (const [path, section] of [
  ["/organizations/:organizationId/people", "people"],
  ["/organizations/:organizationId/teams", "teams"],
  ["/organizations/:organizationId/settings", "settings"],
] as const) {
  app.get(path, (c) => {
    const user = c.get("user");
    const organizationId = c.req.param("organizationId");
    if (!user) return c.redirect(signInHref(organizationRoute(organizationId, `/${section}`)));
    return c.html(renderOrganizationSection(user, organizationId, section));
  });
}

app.get("/organizations/:organizationId", (c) => {
  const user = c.get("user");
  const organizationId = c.req.param("organizationId");
  if (!user) return c.redirect(signInHref(organizationRoute(organizationId)));
  return c.html(renderOrganizationSection(user, organizationId, "overview"));
});

app.get("/accept-invitation/:invitationId", (c) => {
  const invitationId = c.req.param("invitationId");
  const user = c.get("user");
  const returnTo = `/accept-invitation/${encodeURIComponent(invitationId)}`;
  if (!user) return c.redirect(signInHref(returnTo));
  return c.html(renderInvitationPage(user, invitationId));
});

export default app;
