import { Hono } from "hono";
import type { User } from "better-auth/types";
import { renderControlPlanePage, renderTableLoading } from "./control-plane";

const app = new Hono<{ Variables: { user?: User } }>();

const publicationScript = String.raw`
(function(){
  "use strict";
  var ui=window.RendroUI,state=window.__RENDRO_PAGE_STATE__,list=document.getElementById("publication-list"),form=document.getElementById("publication-form"),mode=form.elements.namedItem("trackingMode"),pin=document.getElementById("pin-field"),pinSelect=form.elements.namedItem("pinnedDeploymentId"),query="?organizationId="+encodeURIComponent(state.organizationId)+"&projectId="+encodeURIComponent(state.projectId),loading=${JSON.stringify(renderTableLoading("Loading publications", 5))},loadVersion=0;
  function h(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  var projectNav=document.querySelector(".project-tabs"),deploymentLink=h("a","", "Deployments");deploymentLink.href="/organizations/"+encodeURIComponent(state.organizationId)+"/projects/"+encodeURIComponent(state.projectId)+"#deployments";projectNav.insertBefore(deploymentLink,projectNav.children[1]);projectNav.querySelector(".active").setAttribute("aria-current","page");
  new MutationObserver(function(){if(!list.querySelector("tr"))render([]);}).observe(list,{childList:true});
  async function load(){var version=++loadVersion;list.innerHTML=loading;try{var results=await Promise.all([ui.request("/api/rendro/publications"+query),ui.request("/api/rendro/deployments"+query),ui.request("/api/rendro/projects/get"+query),ui.request("/api/auth/organization/get-full-organization?organizationId="+encodeURIComponent(state.organizationId))]);if(version!==loadVersion)return;var project=results[2].project,organization=results[3];document.querySelectorAll("[data-org-name]").forEach(function(node){node.textContent=organization.name;});document.querySelectorAll("[data-org-mark]").forEach(function(node){node.textContent=organization.name.charAt(0).toUpperCase();});document.querySelector(".cp-page-description").textContent="Stable public URLs for "+project.name+". Publication is explicit and independently revocable.";render(results[0].publications);pinSelect.innerHTML="";results[1].deployments.filter(function(item){return item.status==="active"||item.status==="superseded";}).forEach(function(item){var option=h("option","",item._id.slice(0,12)+" · "+new Date(item.createdAt).toLocaleDateString());option.value=item._id;pinSelect.append(option);});document.getElementById("publication-create").disabled=false;}catch(error){if(version!==loadVersion)return;list.innerHTML='<tr><td colspan="5"><div class="empty compact"><span class="empty-mark">!</span><h2>Unable to load publications</h2><p></p><button class="button" type="button">Try again</button></div></td></tr>';list.querySelector("p").textContent=error.message;list.querySelector("button").addEventListener("click",load);}}
  function render(items){list.innerHTML="";if(!items.length){list.innerHTML='<tr><td colspan="5"><div class="empty compact"><span class="empty-mark">P</span><h2>No public documentation</h2><p>Create a tracked publication for continuously updated docs or pin one immutable release.</p><button class="button primary" type="button">Create publication</button></div></td></tr>';list.querySelector("button").addEventListener("click",function(){ui.openDialog("publication-dialog");});return;}items.forEach(function(item){var tr=h("tr"),url="/p/"+item.slug;var title=h("td");title.dataset.label="Publication";var copy=h("span","cell-primary");copy.append(h("strong","",item.title||item.slug));var link=h("a","cell-secondary",location.origin+url);link.href=url;link.target="_blank";link.rel="noopener";copy.append(link);title.append(copy);var path=h("td","",item.pathPrefix||"Project root");path.dataset.label="Path";var modeCell=h("td");modeCell.dataset.label="Release mode";modeCell.append(h("span","badge "+(item.trackingMode==="pinned"?"warning":"success"),item.trackingMode==="pinned"?"Pinned":"Tracks active"));var status=h("td");status.dataset.label="Status";status.append(h("span","badge success","Public"));var actions=h("td");actions.dataset.label="Actions";var wrap=h("span","row-actions"),copyButton=h("button","button small","Copy URL"),remove=h("button","button danger small","Remove");copyButton.onclick=function(){navigator.clipboard.writeText(location.origin+url);copyButton.textContent="Copied";setTimeout(function(){copyButton.textContent="Copy URL";},1500);};remove.onclick=async function(){if(!confirm("Remove "+(item.title||item.slug)+"? Its public URL will stop working."))return;ui.busy(remove,true);try{await ui.request("/api/rendro/publications/remove",{method:"POST",body:JSON.stringify({organizationId:state.organizationId,projectId:state.projectId,publicationId:item._id})});tr.remove();ui.toast("Publication removed.");}catch(error){ui.busy(remove,false);ui.toast(error.message,"error");}};wrap.append(copyButton,remove);actions.append(wrap);tr.append(title,path,modeCell,status,actions);list.append(tr);});}
  mode.onchange=function(){pin.hidden=mode.value!=="pinned";};form.onsubmit=async function(event){event.preventDefault();var button=form.querySelector("button[type=submit]"),error=document.getElementById("publication-error");error.textContent="";ui.busy(button,true);try{await ui.request("/api/rendro/publications",{method:"POST",body:JSON.stringify({organizationId:state.organizationId,projectId:state.projectId,slug:form.elements.namedItem("slug").value.trim(),title:form.elements.namedItem("title").value.trim(),pathPrefix:form.elements.namedItem("pathPrefix").value.trim(),entryFile:form.elements.namedItem("entryFile").value.trim(),trackingMode:mode.value,pinnedDeploymentId:mode.value==="pinned"?pinSelect.value:undefined})});document.getElementById("publication-dialog").close();form.reset();pin.hidden=true;ui.busy(button,false);ui.toast("Publication created.");await load();}catch(reason){error.textContent=reason.message;ui.busy(button,false);}};
  load();
})();
`;

function renderPage(user: User, organizationId: string, projectId: string): string {
  const base = `/organizations/${encodeURIComponent(organizationId)}/projects/${encodeURIComponent(projectId)}`;
  return renderControlPlanePage({
    user,
    title: "Publications",
    eyebrow: "Public access",
    heading: "Publications",
    description: "Expose an explicit project path through a stable anonymous URL.",
    organizationId,
    projectId,
    active: "projects",
    actions: `<a class="button" href="${base}">Project overview</a><button class="button primary" id="publication-create" type="button" data-dialog-open="publication-dialog" disabled>Create publication</button>`,
    state: { organizationId, projectId },
    content: `<nav class="project-tabs" aria-label="Project sections"><a href="${base}">Overview</a><a class="active" href="${base}/publications">Publications</a><a href="${base}/shares">Private shares</a></nav><section class="panel"><div class="table-wrap"><table class="data-table publication-table"><thead><tr><th>Publication</th><th>Path</th><th>Release mode</th><th>Status</th><th>Actions</th></tr></thead><tbody id="publication-list">${renderTableLoading("Loading publications", 5)}</tbody></table></div></section><dialog class="cp-dialog" id="publication-dialog"><div class="dialog-head"><div><h2>Create publication</h2><p>The entry file and every document must remain inside the selected path prefix.</p></div><button class="dialog-close" type="button" data-dialog-close aria-label="Close publication dialog">Close</button></div><form id="publication-form"><div class="dialog-body"><div class="form-grid"><label class="field"><span>Public URL slug</span><input class="input" name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxlength="80" placeholder="product-docs"></label><label class="field"><span>Title</span><input class="input" name="title" required maxlength="100" placeholder="Product documentation"></label><label class="field"><span>Path prefix</span><input class="input" name="pathPrefix" placeholder="reference"><small>Leave empty to publish from the project root.</small></label><label class="field"><span>Entry file</span><input class="input" name="entryFile" value="index.html" required></label><label class="field"><span>Release mode</span><select class="select" name="trackingMode"><option value="track_active">Track active deployment</option><option value="pinned">Pin one deployment</option></select></label><label class="field" id="pin-field" hidden><span>Deployment</span><select class="select" name="pinnedDeploymentId"></select></label><p class="message error" id="publication-error" role="alert"></p></div></div><div class="dialog-footer"><button class="button" type="button" data-dialog-close>Cancel</button><button class="button primary" type="submit"><span class="button-label">Create publication</span></button></div></form></dialog><style>.publication-table{min-width:760px}.row-actions{display:flex;gap:6px}.project-tabs{display:flex;gap:4px;margin-bottom:16px;padding-bottom:1px;border-bottom:1px solid var(--cp-border);overflow-x:auto}.project-tabs a{position:relative;padding:9px 12px;color:var(--cp-muted);text-decoration:none}.project-tabs a:hover,.project-tabs a.active{color:var(--cp-strong)}.project-tabs a.active:after{content:"";position:absolute;inset:auto 8px -2px;height:2px;background:var(--cp-accent)}</style>`,
    script: publicationScript,
  });
}

app.get("/organizations/:organizationId/projects/:projectId/publications", (c) => {
  const organizationId = c.req.param("organizationId");
  const projectId = c.req.param("projectId");
  const user = c.get("user");
  const returnTo = `/organizations/${encodeURIComponent(organizationId)}/projects/${encodeURIComponent(projectId)}/publications`;
  if (!user) return c.redirect(`/sign-in?returnTo=${encodeURIComponent(returnTo)}`);
  return c.html(renderPage(user, organizationId, projectId));
});

export default app;
