import { Hono } from "hono";
import type { User } from "better-auth/types";
import { renderControlPlanePage, renderTableLoading } from "./control-plane";
import { publicationLoadingPage } from "./management-loading-pages";

const app = new Hono<{ Variables: { user?: User } }>();

const publicationScript = String.raw`
(function(){
  "use strict";
  var ui=window.RendroUI.createPageScope?window.RendroUI.createPageScope():window.RendroUI,state=window.__RENDRO_PAGE_STATE__,list=document.getElementById("publication-list"),form=document.getElementById("publication-form"),mode=form.elements.namedItem("trackingMode"),pin=document.getElementById("pin-field"),pinSelect=form.elements.namedItem("pinnedDeploymentId"),query="?organizationId="+encodeURIComponent(state.organizationId)+"&projectId="+encodeURIComponent(state.projectId),loading=${JSON.stringify(renderTableLoading("Loading publications", 5))},loadVersion=0,publications=[],canManage=false;
  function active(){return !ui.isActive||ui.isActive();}
  function h(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
  function setAccess(organization){var member=(organization.members||[]).find(function(candidate){return candidate.userId===state.userId;}),roles=member?String(member.role||"").split(",").map(function(role){return role.trim();}):[];canManage=roles.some(function(role){return role==="owner"||role==="admin";});var trigger=document.getElementById("publication-create"),note=document.getElementById("publication-access-note"),dialog=document.getElementById("publication-dialog");trigger.hidden=!canManage;trigger.disabled=!canManage;note.hidden=canManage;form.querySelectorAll("input,select,button[type=submit]").forEach(function(control){control.disabled=!canManage;});if(!canManage&&dialog.open)dialog.close();}
  async function load(showLoading){var version=++loadVersion;if(showLoading!==false)list.innerHTML=loading;try{var results=await Promise.all([ui.request("/api/rendro/publications"+query),ui.request("/api/rendro/deployments"+query),ui.request("/api/rendro/projects/get"+query),ui.request("/api/auth/organization/get-full-organization?organizationId="+encodeURIComponent(state.organizationId))]);if(version!==loadVersion||!active())return;var project=results[2].project,organization=results[3];document.querySelectorAll("[data-org-name]").forEach(function(node){if(node.textContent!==organization.name)node.textContent=organization.name;});document.querySelectorAll("[data-org-mark]").forEach(function(node){var initial=organization.name.charAt(0).toUpperCase();if(node.textContent!==initial)node.textContent=initial;});setAccess(organization);document.querySelector(".cp-page-description").textContent="Stable public URLs for "+project.name+". Publication is explicit and independently revocable.";publications=results[0].publications||[];render(publications);pinSelect.innerHTML="";results[1].deployments.filter(function(item){return item.status==="active"||item.status==="superseded";}).forEach(function(item){var option=h("option","",item._id.slice(0,12)+" · "+new Date(item.createdAt).toLocaleDateString());option.value=item._id;pinSelect.append(option);});}catch(error){if(version!==loadVersion||!active())return;list.innerHTML='<tr><td colspan="5"><div class="empty compact"><span class="empty-mark">!</span><h2>Unable to load publications</h2><p></p><button class="button" type="button">Try again</button></div></td></tr>';list.querySelector("p").textContent=error.message;list.querySelector("button").addEventListener("click",load);}}
  function render(items){list.innerHTML="";if(!items.length){list.innerHTML='<tr><td colspan="5"><div class="empty compact"><span class="empty-mark material-symbols-outlined" aria-hidden="true">public</span><h2>No public documentation</h2><p>'+(canManage?'Create a tracked publication for continuously updated docs or pin one immutable release.':'No publication has been created for this project.')+'</p>'+(canManage?'<button class="button primary" type="button">Create publication</button>':'')+'</div></td></tr>';var create=list.querySelector("button");if(create)create.addEventListener("click",function(){ui.openDialog("publication-dialog");});return;}items.forEach(function(item){var tr=h("tr"),url="/p/"+item.slug;var title=h("td");title.dataset.label="Publication";var copy=h("span","cell-primary");copy.append(h("strong","",item.title||item.slug));var link=h("a","cell-secondary",location.origin+url);link.href=url;link.target="_blank";link.rel="noopener";copy.append(link);title.append(copy);var path=h("td","",item.pathPrefix||"Project root");path.dataset.label="Path";var modeCell=h("td");modeCell.dataset.label="Release mode";modeCell.append(h("span","badge "+(item.trackingMode==="pinned"?"warning":"success"),item.trackingMode==="pinned"?"Pinned":"Tracks active"));var status=h("td");status.dataset.label="Status";status.append(h("span","badge success","Public"));var actions=h("td");actions.dataset.label="Actions";var wrap=h("span","row-actions"),copyButton=h("button","button small","Copy URL");copyButton.onclick=function(){ui.copyText(copyButton,location.origin+url,"Copy URL").catch(function(){ui.toast("Unable to copy. Select the URL and copy it manually.","error");});};wrap.append(copyButton);if(canManage){var remove=h("button","button danger small","Remove");remove.onclick=async function(){if(!confirm("Remove "+(item.title||item.slug)+"? Its public URL will stop working."))return;ui.busy(remove,true);try{await ui.request("/api/rendro/publications/remove",{method:"POST",body:JSON.stringify({organizationId:state.organizationId,projectId:state.projectId,publicationId:item._id})});if(!active())return;publications=publications.filter(function(candidate){return candidate._id!==item._id;});render(publications);ui.toast("Publication removed.");}catch(error){if(!active())return;ui.busy(remove,false);ui.toast(error.message,"error");}};wrap.append(remove);}actions.append(wrap);tr.append(title,path,modeCell,status,actions);list.append(tr);});}
  mode.onchange=function(){pin.hidden=mode.value!=="pinned";};form.onsubmit=async function(event){event.preventDefault();var button=form.querySelector("button[type=submit]"),error=document.getElementById("publication-error");error.textContent="";if(!canManage){error.textContent="Only organization owners and admins can create publications.";return;}ui.busy(button,true);try{var result=await ui.request("/api/rendro/publications",{method:"POST",body:JSON.stringify({organizationId:state.organizationId,projectId:state.projectId,slug:form.elements.namedItem("slug").value.trim(),title:form.elements.namedItem("title").value.trim(),pathPrefix:form.elements.namedItem("pathPrefix").value.trim(),entryFile:form.elements.namedItem("entryFile").value.trim(),trackingMode:mode.value,pinnedDeploymentId:mode.value==="pinned"?pinSelect.value:undefined})});if(!active())return;document.getElementById("publication-dialog").close();form.reset();pin.hidden=true;ui.busy(button,false);if(result.publication)publications=publications.concat([result.publication]);render(publications);ui.toast("Publication created.");}catch(reason){if(!active())return;error.textContent=reason.message;ui.busy(button,false);}};
  load(false);
})();
`;

function renderPage(user: User, organizationId: string, projectId: string): string {
  return renderControlPlanePage({
    ...publicationLoadingPage(organizationId, projectId),
    user,
    title: "Publications",
    organizationId,
    projectId,
    active: "projects",
    state: { organizationId, projectId, userId: user.id },
    content: `${publicationLoadingPage(organizationId, projectId).content}<dialog class="cp-dialog" id="publication-dialog"><div class="dialog-head"><div><h2>Create publication</h2><p>The entry file and every document must remain inside the selected path prefix.</p></div><button class="dialog-close" type="button" data-dialog-close aria-label="Close publication dialog">Close</button></div><form id="publication-form"><div class="dialog-body"><div class="form-grid"><label class="field"><span>Public URL slug</span><input class="input" name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" maxlength="80" placeholder="product-docs" disabled></label><label class="field"><span>Title</span><input class="input" name="title" required maxlength="100" placeholder="Product documentation" disabled></label><label class="field"><span>Path prefix</span><input class="input" name="pathPrefix" placeholder="reference" disabled><small>Leave empty to publish from the project root.</small></label><label class="field"><span>Entry file</span><input class="input" name="entryFile" value="index.html" required disabled></label><label class="field"><span>Release mode</span><select class="select" name="trackingMode" disabled><option value="track_active">Track active deployment</option><option value="pinned">Pin one deployment</option></select></label><label class="field" id="pin-field" hidden><span>Deployment</span><select class="select" name="pinnedDeploymentId" disabled></select></label><p class="message error" id="publication-error" role="alert"></p></div></div><div class="dialog-footer"><button class="button" type="button" data-dialog-close>Cancel</button><button class="button primary" type="submit" disabled><span class="button-label">Create publication</span></button></div></form></dialog>`,
    script: publicationScript,
  });
}

app.get("/organizations/:organizationId/projects/:projectId/publications", (c) => {
  const organizationId = c.req.param("organizationId");
  const projectId = c.req.param("projectId");
  const user = c.get("user");
  const returnTo = `/organizations/${encodeURIComponent(organizationId)}/projects/${encodeURIComponent(projectId)}/publications`;
  if (!user) return c.redirect(`/sign-in?returnTo=${encodeURIComponent(returnTo)}`);
  return c.html(renderPage(user, organizationId, projectId));
});

export default app;
